'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{webcrypto}=require('node:crypto');
function load(){const window={crypto:webcrypto,btoa:v=>Buffer.from(v,'binary').toString('base64'),navigator:{onLine:true}};const context=vm.createContext({window,Uint8Array,unescape,encodeURIComponent,decodeURIComponent,queueMicrotask,structuredClone,console,setTimeout,clearTimeout,AbortController});for(const name of['js/domain/productLimits.js','js/domain/accountSyncModel.js','js/domain/accountSyncMerge.js','js/data/accountSyncController.js','js/testing/accountSyncHarness.js','js/data/favoriteAdditions.js','js/services/favoriteResolverClient.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',name),'utf8'),context);return window;}
async function fixture({resolver:provided,online=true,state}={}){const w=load(),h=w.PogoTesting.accountSyncHarness.createMultiDeviceHarness(),device=h.createDevice('one',{online,...(state?{state}:{})});await device.start();let current=true,calls=[];const resolver=provided||{resolve:async handles=>{calls.push([...handles]);return handles.map(handle=>({handle,status:'resolved',targetUid:'uid-'+handle,canonicalHandle:handle}));}};const additions=w.PogoData.favoriteAdditions.createFavoriteAdditions({ownerUid:h.ownerUid,journal:device.journal,controller:device.controller,resolver,sessionCurrent:()=>current,now:h.clock});return{w,h,device,resolver,additions,calls,switchAccount(){current=false;additions.close();}};}
const last=(value,handle)=>[...value.rows].reverse().find(row=>row.handle===handle);
test('ensure repeated on an existing Favorite preserves tags and never toggles or creates another operation',async()=>{
 const f=await fixture();await f.additions.ensure(['Target']);await f.h.settle();const saved=f.h.server.snapshot().favorites['uid-Target'];
 await f.device.controller.patchEntity({entityType:'favorite',entityId:'uid-Target',patch:{'tagIds/tag_group':true}});await f.h.settle();const tagged=JSON.stringify(f.h.server.snapshot().favorites['uid-Target']),operations=f.device.state.operations.size;
 await f.additions.ensure(['Target']);await f.additions.retry(['Target']);await f.h.settle();assert.equal(f.device.state.operations.size,operations);assert.equal(JSON.stringify(f.h.server.snapshot().favorites['uid-Target']),tagged);assert.equal(last(await f.additions.snapshot(),'Target').state,'confirmed');assert.equal(saved.deleted,false);await f.device.controller.deactivate();
});
test('100 selected targets use two bounded batches and queue through the same path',async()=>{
 const f=await fixture();await f.additions.ensure(Array.from({length:100},(_,i)=>'T'+i));await f.h.settle();assert.deepEqual(f.calls.map(x=>x.length),[50,50]);assert.equal(f.h.server.entities.size,100,JSON.stringify((await f.additions.snapshot()).rows.filter(row=>row.state==='unsuccessful').map(row=>row.code)));assert.equal((await f.additions.snapshot()).remaining,0);await assert.rejects(f.additions.ensure(['Extra']),{code:'favorite/capacity-exceeded'});await f.device.controller.deactivate();
});
test('partial resolution failure retains only unsuccessful work for retry',async()=>{
 let fail=true;const calls=[];const f=await fixture({resolver:{resolve:async handles=>{calls.push([...handles]);return handles.map(handle=>fail&&handle==='Later'?{handle,status:'unavailable'}:{handle,status:'resolved',targetUid:'uid-'+handle,canonicalHandle:handle});}}});
 await f.additions.ensure(['Now','Later']);await f.h.settle();assert.equal(last(await f.additions.snapshot(),'Later').state,'unsuccessful');const id=f.h.server.snapshot().favorites['uid-Now'].lifecycleMutation;
 fail=false;await f.additions.ensure(['Later']);await f.h.settle();assert.deepEqual(calls,[['Now','Later'],['Later']]);assert.equal(f.h.server.snapshot().favorites['uid-Now'].lifecycleMutation,id);assert.equal(f.h.server.entities.size,2);await f.device.controller.deactivate();
});
test('offline durable operation survives a new addition runtime and retains its exact operation id',async()=>{
 const f=await fixture({online:false});await f.additions.ensure(['Offline']);assert.equal(last(await f.additions.snapshot(),'Offline').state,'pending');assert.equal(f.h.server.entities.size,0);const id=[...f.device.state.operations.keys()][0];f.additions.close();await f.device.controller.deactivate();
 const second=f.h.createDevice('restarted',{state:f.device.state});await second.start();const additions=f.w.PogoData.favoriteAdditions.createFavoriteAdditions({ownerUid:f.h.ownerUid,journal:second.journal,controller:second.controller,resolver:f.resolver,sessionCurrent:()=>true,now:f.h.clock});await additions.resume();await f.h.settle();assert.equal(f.h.server.snapshot().favorites['uid-Offline'].lifecycleMutation,id);assert.equal(last(await additions.snapshot(),'Offline').state,'confirmed');await second.controller.deactivate();
});
test('a removal during resolution cannot be resurrected by the late response',async()=>{
 const f=await fixture();await f.device.controller.ensureFavorite({targetUid:'uid-Target',displayName:'Target'});await f.h.settle();
 let release;const response=new Promise(r=>release=r);const resolver={resolve:()=>response};const additions=f.w.PogoData.favoriteAdditions.createFavoriteAdditions({ownerUid:f.h.ownerUid,journal:f.device.journal,controller:f.device.controller,resolver,sessionCurrent:()=>true,now:f.h.clock});
 const adding=additions.ensure(['Target']);for(let i=0;i<20&&!f.device.state.meta.size;i++)await new Promise(r=>setImmediate(r));
 await f.device.controller.deleteEntity({entityType:'favorite',entityId:'uid-Target'});await f.h.settle();release([{handle:'Target',status:'resolved',targetUid:'uid-Target',canonicalHandle:'Target'}]);await adding;assert.equal(last(await additions.snapshot(),'Target').state,'unsuccessful');assert.equal(f.h.server.snapshot().favorites['uid-Target'].deleted,true);await additions.retry(['Target']);assert.equal(f.h.server.snapshot().favorites['uid-Target'].deleted,true);await f.device.controller.deactivate();
});
test('preserved Favorite is reviewed separately and does not block another new Favorite',async()=>{
 const f=await fixture();await f.device.journal.putRecoveryCandidate({ownerUid:f.h.ownerUid,schemaVersion:1,candidateId:'candidate-preserved',entityType:'favorite',entityId:'unresolved',values:{displayName:'Old',tagIds:['tag_old']},createdAt:1});
 await f.additions.ensure(['Old','New']);await f.h.settle();assert.equal(last(await f.additions.snapshot(),'Old').code,'account-sync/entity-review-required');assert.equal(f.h.server.entities.size,1);assert.equal((await f.device.journal.listRecoveryCandidates())[0].resolved,undefined);await f.device.controller.deactivate();
});
test('account change discards presentation and a late resolver response cannot enqueue under any account',async()=>{
 let release;const response=new Promise(r=>release=r);const f=await fixture({resolver:{resolve:()=>response}});const adding=f.additions.ensure(['Target']);for(let i=0;i<20&&!f.device.state.meta.size;i++)await new Promise(r=>setImmediate(r));f.switchAccount();release([{handle:'Target',status:'resolved',targetUid:'uid-Target',canonicalHandle:'Target'}]);await assert.rejects(adding,{code:'favorite/session-changed'});assert.equal(f.device.state.operations.size,0);assert.equal(f.h.server.entities.size,0);await f.device.controller.deactivate();
});
test('cancel during resolution prevents unsent additions and never undoes confirmed additions',async()=>{
 const f=await fixture();await f.additions.ensure(['Saved']);await f.h.settle();await f.additions.cancel(['Saved']);assert.equal(f.h.server.snapshot().favorites['uid-Saved'].deleted,false);
 let release;f.resolver.resolve=()=>new Promise(r=>release=r);const adding=f.additions.ensure(['Later']);for(let i=0;i<20&&!release;i++)await new Promise(r=>setImmediate(r));const cancelling=f.additions.cancel(['Later']);release([{handle:'Later',status:'resolved',targetUid:'uid-Later',canonicalHandle:'Later'}]);await adding;await cancelling;assert.equal(last(await f.additions.snapshot(),'Later').state,'cancelled');assert.equal(f.h.server.entities.size,1);await f.device.controller.deactivate();
});
test('resolver client rejects mismatched identities, extra data and self targets',()=>{
 const api=load().PogoServices.favoriteResolverClient;
 for(const row of[{handle:'X',status:'resolved',targetUid:'owner',canonicalHandle:'X'},{handle:'X',status:'resolved',targetUid:'target',canonicalHandle:'x'},{handle:'X',status:'resolved',targetUid:'target',canonicalHandle:'X',privateNote:'secret'}])assert.throws(()=>api.validateResponse({version:1,results:[row]},['X'],'owner'),{code:'favorite/response-invalid'});
});
