const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('fs');
const os=require('os');
const path=require('path');
const {privateRoot,resolveOutput,buildPrivateReport,writePrivateReport,aggregateLines}=require('../scripts/lib/private-identity-report.cjs');
const {run}=require('../scripts/audit-uid-handle-mappings.js');
const {parseArgs}=require('../scripts/audit-uid-handle-mappings.js');
function sample(){return{normalizationContract:'trainer-name-nfkc-lower-v1',staleWarning:'stale',totalRecords:1,classificationCounts:{ready_for_mapping:1},records:[{internalKey:'username:SecretTrainer',trainerName:'SecretTrainer',normalizedTrainerName:'secrettrainer',uid:'private-uid',classification:'ready_for_mapping',reasonCodes:[],seedEligible:false,facts:{providers:['password']}}]};}
const metadata={source:'fixture',targetVerified:false,sourceCounts:{loginDirectory:1,users:1,authIndex:1,admins:0,authIdentities:1},sourceSnapshotHashes:{loginDirectory:'a',users:'b',authIndex:'c',admins:'d',authInput:'e'}};
test('report path is confined and report/file permissions are private',()=>{assert.throws(()=>resolveOutput('../outside.json'),error=>error.code==='report_path_outside_private_root');const file=path.join(privateRoot,'reports','permission-test.json');try{writePrivateReport(buildPrivateReport(sample(),metadata,{secret:Buffer.from('one')}),file);assert.equal(fs.statSync(file).mode&0o777,0o600);assert.equal(fs.statSync(path.dirname(file)).mode&0o777,0o700);}finally{fs.rmSync(file,{force:true});}});
test('report writer rejects a symlinked parent that escapes the private root',()=>{const outside=fs.mkdtempSync(path.join(os.tmpdir(),'uid-report-outside-'));const link=path.join(privateRoot,'escape-link');try{fs.mkdirSync(privateRoot,{recursive:true});fs.rmSync(link,{force:true,recursive:true});fs.symlinkSync(outside,link);assert.throws(()=>writePrivateReport(buildPrivateReport(sample(),metadata,{secret:Buffer.from('one')}),path.join(link,'report.json')),error=>error.code==='report_path_outside_private_root');assert.equal(fs.existsSync(path.join(outside,'report.json')),false);}finally{fs.rmSync(link,{force:true,recursive:true});fs.rmSync(outside,{force:true,recursive:true});}});
test('private IDs are report-specific and not stable or directly guessable',()=>{const a=buildPrivateReport(sample(),metadata,{secret:Buffer.from('one')});const b=buildPrivateReport(sample(),metadata,{secret:Buffer.from('two')});assert.notEqual(a.records[0].recordId,b.records[0].recordId);assert.doesNotMatch(a.records[0].recordId,/SecretTrainer|private-uid/i);});
test('reports retain hashes/version/stale warning and contain no seed-capable artifacts',()=>{const report=buildPrivateReport(sample(),metadata,{secret:Buffer.from('one')});const text=JSON.stringify(report);assert.equal(report.toolVersion,'uid-handle-dry-run-v1');assert.equal(report.records[0].seedEligible,false);assert.ok(report.source.snapshotHashes);assert.doesNotMatch(text,/approvalManifest|firebaseUpdate|rollbackWrite|seedCommand|reservationRequest/);assert.doesNotMatch(text,/@example|authToken|credential/);});
test('aggregate console lines contain counts only, not private identities',()=>{const lines=aggregateLines(buildPrivateReport(sample(),metadata,{secret:Buffer.from('one')})).join('\n');assert.doesNotMatch(lines,/SecretTrainer|secrettrainer|private-uid/);assert.match(lines,/ready_for_mapping: 1/);});
test('synthetic CLI output is aggregate-only and writes a private report',async()=>{const output=path.join(privateRoot,'reports','cli-test.json');const lines=[];const old=console.log;console.log=value=>lines.push(String(value));try{await run(['--source','fixture','--input','tests/fixtures/uid-handle-rtdb.synthetic.json','--auth-input','tests/fixtures/uid-handle-auth.synthetic.json','--output',path.relative(path.resolve(__dirname,'..'),output)]);}finally{console.log=old;}const text=lines.join('\n');assert.doesNotMatch(text,/ReadyTrainer|ProtectedTrainer|synthetic-uid/);assert.equal(fs.statSync(output).mode&0o777,0o600);fs.rmSync(output,{force:true});});
test('CLI rejects service-account and other unapproved credential options',()=>{assert.throws(()=>parseArgs(['--service-account','private.json']),/Unsupported CLI option/);assert.throws(()=>parseArgs(['--credential','secret']),/Unsupported CLI option/);});
test('tracked package and CLI expose no seed or migration-write command',()=>{const packageJson=JSON.parse(fs.readFileSync(path.join(__dirname,'../package.json'),'utf8'));assert.equal(Object.keys(packageJson.scripts).some(key=>/seed|migrate|reserve/i.test(key)),false);const cli=fs.readFileSync(path.join(__dirname,'../scripts/audit-uid-handle-mappings.js'),'utf8');assert.doesNotMatch(cli,/firebaseUpdate|approvalManifest|reservationRequest|seedEligible\s*:\s*true/);});
