const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');

const root=path.resolve(__dirname,'..');
function domain(){const context={window:{}};vm.createContext(context);for(const file of ['trainerPreferences.js','shareActivationPlanning.js'])vm.runInContext(fs.readFileSync(path.join(root,'js/domain',file),'utf8'),context,{filename:file});return context.window.PogoDomain.shareActivationPlanning;}
function record(overrides={}){return{reviewerDecision:'confirmed_valid_identity',seedEligible:false,queue:'individually_reviewable',conflict:false,publicProjectionStatus:'valid_complete',linkageStatus:'consistent',evidenceHash:'private-evidence-digest',...overrides};}
function eligibility(records=[record()],overrides={}){return domain().oneRecordEligibility({records,sourceAuditHash:'source',expectedSourceAuditHash:'source',reviewReportHash:'review',expectedReviewReportHash:'review',freshProductionAudit:true,ownerApproval:true,recordDryRunReviewed:true,rollbackReviewed:true,...overrides});}

test('one-record eligibility requires every separately reviewed gate',()=>{const value=eligibility();assert.equal(value.ok,true);assert.equal(value.status,'eligible_for_separate_seed_approval');assert.equal(value.seedEligible,false);assert.equal(value.requiresExplicitSeedEligibilityApproval,true);});
test('diagnostic confirmation alone remains insufficient',()=>{const value=eligibility([record()],{ownerApproval:false,recordDryRunReviewed:false});assert.equal(value.ok,false);assert.deepEqual(Array.from(value.blockers),['explicitOwnerApproval','recordDryRunReviewed']);assert.equal(value.seedEligible,false);});
test('fresh hash drift conflict protected and incomplete states block eligibility',()=>{assert.equal(eligibility([record()],{expectedSourceAuditHash:'changed'}).ok,false);assert.equal(eligibility([record({queue:'protected_accounts'})]).ok,false);assert.equal(eligibility([record({queue:'duplicate_conflicts'})]).ok,false);assert.equal(eligibility([record({publicProjectionStatus:'projection_incomplete'})]).ok,false);});
test('zero or multiple records are rejected and bulk mode does not exist',()=>{assert.equal(eligibility([]).code,'share-activation/exactly-one-record-required');assert.equal(eligibility([record(),record()]).code,'share-activation/exactly-one-record-required');});
test('UID seed dry run plans only five reviewed paths and performs zero writes',()=>{const api=domain(),value=api.uidSeedDryRun({records:[record()],eligibility:eligibility(),baselineFingerprints:{},proposedVisibility:'private',fingerprint:value=>`sha256:${JSON.stringify(value).length}`});assert.equal(value.ok,true);assert.equal(value.writes,0);assert.equal(value.seedEligible,false);assert.equal(value.applySupported,false);assert.equal(value.bulkSupported,false);assert.equal(value.targets.length,5);assert.equal(value.identityRepair,false);assert.equal(value.ownedListProjectionGeneration,false);});
test('UID seed dry run refuses incomplete projections or missing approval',()=>{const api=domain();assert.equal(api.uidSeedDryRun({records:[record({publicProjectionStatus:'projection_incomplete'})],eligibility:{ok:true},fingerprint:()=>''}).code,'share-activation/complete-projection-required');assert.equal(api.uidSeedDryRun({records:[record()],eligibility:{ok:false},fingerprint:()=>''}).code,'share-activation/eligibility-required');});
test('preference dry run requires exact UID and username ownership plus completed reads',()=>{const api=domain();let value=api.preferenceMigrationDryRun({activeIdentity:{uid:'a',username:'User'},partitionIdentity:{uid:'b',username:'User'},serverReadsComplete:true});assert.equal(value.code,'trainer-preferences/partition-mismatch');value=api.preferenceMigrationDryRun({activeIdentity:{uid:'a',username:'User'},partitionIdentity:{uid:'a',username:'User'},serverReadsComplete:false});assert.equal(value.code,'trainer-preferences/server-read-required');});
test('preference dry run merges bounded favorites recents history and never deletes local state',()=>{const value=domain().preferenceMigrationDryRun({activeIdentity:{uid:'a',username:'User'},partitionIdentity:{uid:'a',username:'User'},serverReadsComplete:true,userApproved:true,local:{favorites:{owner:{trainerName:'Trainer',addedAt:20}},recents:{'00':{ownerUid:'owner',trainerName:'Trainer',lastOpenedAt:30}},history:{}},server:{favorites:{owner:{trainerName:'Trainer',addedAt:10}},recents:{},history:{}}});assert.equal(value.ok,true);assert.equal(value.writes,0);assert.equal(value.applySupported,false);assert.equal(value.deleteLocal,false);assert.equal(value.counts.favorites,1);assert.equal(value.counts.recents,1);assert.equal(value.recentsBounded,true);});
test('tag normalization conflicts are surfaced rather than silently merged',()=>{const value=domain().preferenceMigrationDryRun({activeIdentity:{uid:'a',username:'User'},partitionIdentity:{uid:'a',username:'User'},serverReadsComplete:true,local:{tags:{tag_one:{label:'Raid',active:true,createdAt:1,updatedAt:1}}},server:{tags:{tag_two:{label:'ＲＡＩＤ',active:true,createdAt:1,updatedAt:1}}}});assert.equal(value.ok,false);assert.equal(value.status,'conflict_or_invalid');assert.equal(value.tagConflictCount,1);assert.equal(value.writes,0);});
test('preference dry run includes deterministic private tag claims without making them writable',()=>{const value=domain().preferenceMigrationDryRun({activeIdentity:{uid:'a',username:'User'},partitionIdentity:{uid:'a',username:'User'},serverReadsComplete:true,local:{tags:{tag_one:{label:'Raid Friends',active:true,createdAt:20,updatedAt:30}}},server:{tags:{tag_one:{label:'Raid Friends',active:true,createdAt:10,updatedAt:20}}}});assert.equal(value.ok,true);assert.equal(value.privatePlan.trainerTags.tag_one.createdAt,10);assert.equal(value.privatePlan.trainerTags.tag_one.updatedAt,30);assert.equal(Object.values(value.privatePlan.trainerTagLabels)[0],'tag_one');assert.equal(value.writes,0);assert.equal(value.deleteLocal,false);});
test('planner source has no network apply write or production adapter capability',()=>{const source=fs.readFileSync(path.join(root,'js/domain/shareActivationPlanning.js'),'utf8');assert.doesNotMatch(source,/fetch\s*\(|firebase-admin|https?:\/\/|--apply|databaseURL|serviceAccount/i);assert.doesNotMatch(source,/function\s+(?:set|update|remove|write)/i);});
