const test=require('node:test');
const assert=require('node:assert/strict');
const crypto=require('node:crypto');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');

const root=path.resolve(__dirname,'..');
function domain(){
  const context={window:{}};vm.createContext(context);
  for(const file of ['trainerNames.js','trainerPreferences.js','trustedBackendContracts.js'])vm.runInContext(fs.readFileSync(path.join(root,'js/domain',file),'utf8'),context,{filename:file});
  return context.window.PogoDomain.trustedBackendContracts;
}
const auth={authUid:'uid-a',appCheckValid:true,requestId:'request-1'};
const sha256=value=>crypto.createHash('sha256').update(value).digest('hex');

test('handle reservation uses canonical NFKC and case normalization',()=>{const value=domain().reserveHandle({...auth,requestedHandle:'  ＴｅｓｔUser  ',accountUid:'uid-a'});assert.equal(value.ok,true);assert.equal(value.normalizedHandle,'testuser');assert.equal(value.displayHandle,'TestUser');});
test('handle collisions and UID reassignment are rejected',()=>{const api=domain();assert.equal(api.reserveHandle({...auth,requestedHandle:'TestUser',existingClaimUid:'uid-b'}).code,'trusted-backend/handle-collision');assert.equal(api.reserveHandle({...auth,requestedHandle:'TestUser',accountUid:'uid-b'}).code,'trusted-backend/uid-ownership-mismatch');});
test('invalid Firebase handle keys and oversized handles are rejected',()=>{const api=domain();assert.equal(api.reserveHandle({...auth,requestedHandle:'bad/name'}).code,'trusted-backend/handle-key-invalid');assert.equal(api.reserveHandle({...auth,requestedHandle:'a'.repeat(65)}).code,'trusted-backend/handle-too-long');});
test('tag claims are isolated per authenticated viewer and preserve display case',()=>{const value=domain().claimTagLabel({...auth,viewerUid:'uid-a',tagId:'tag_one',action:'claim',label:'  Raid Friends '});assert.equal(value.ok,true);assert.equal(value.displayLabel,'Raid Friends');assert.equal(value.normalizedLabel,'raid friends');assert.deepEqual(Array.from(value.allowedTargets),['userPreferences/{viewerUid}/trainerTags/{tagId}','userPreferences/{viewerUid}/trainerTagLabels/{labelKey}']);assert.equal(domain().claimTagLabel({...auth,viewerUid:'uid-b',tagId:'tag_one',action:'claim',label:'Raid'}).code,'trusted-backend/tag-namespace-denied');});
test('tag label collisions rename and soft deletion have bounded targets',()=>{const api=domain();assert.equal(api.claimTagLabel({...auth,viewerUid:'uid-a',tagId:'tag_two',action:'rename',label:'Raid',existingClaimTagId:'tag_one'}).code,'trusted-backend/tag-label-collision');assert.equal(api.claimTagLabel({...auth,viewerUid:'uid-a',tagId:'tag_one',action:'soft_delete'}).operation,'tag_soft_delete');});
test('history verifies actual count canonical fingerprint and public-only shape',()=>{const api=domain(),entries={a:{category:'wishlist',fingerprint:'one'},b:{category:'gmax',fingerprint:'two'}};const fingerprint=sha256(api.stable(entries));const value=api.verifyHistory({...auth,viewerUid:'uid-a',ownerUid:'uid-owner',entries,entryCount:2,declaredFingerprint:fingerprint,sha256,lastSeenShareVersion:2,lastSeenUpdatedAt:20,previous:{lastSeenShareVersion:1,lastSeenUpdatedAt:10}});assert.equal(value.ok,true);assert.equal(value.entryCount,2);});
test('history rejects count mismatch private fields oversized snapshots and same-version conflicts',()=>{const api=domain(),entries={a:{category:'wishlist',fingerprint:'one'}},fingerprint=sha256(api.stable(entries));assert.equal(api.verifyHistory({...auth,viewerUid:'uid-a',ownerUid:'x',entries,entryCount:0,declaredFingerprint:fingerprint,sha256,lastSeenShareVersion:1,lastSeenUpdatedAt:1}).code,'trusted-backend/history-count-mismatch');assert.equal(api.verifyHistory({...auth,viewerUid:'uid-a',ownerUid:'x',entries:{a:{category:'wishlist',fingerprint:'one',privateNote:'no'}},entryCount:1,declaredFingerprint:'x',sha256,lastSeenShareVersion:1,lastSeenUpdatedAt:1}).code,'trainer-preferences/history-entry-invalid');const huge=Object.fromEntries(Array.from({length:1501},(_,i)=>[String(i),{category:'wishlist',fingerprint:'x'}]));assert.equal(api.verifyHistory({...auth,viewerUid:'uid-a',ownerUid:'x',entries:huge,entryCount:1501,declaredFingerprint:'x',sha256,lastSeenShareVersion:1,lastSeenUpdatedAt:1}).code,'trainer-preferences/history-too-large');assert.equal(api.verifyHistory({...auth,viewerUid:'uid-a',ownerUid:'x',entries,entryCount:1,declaredFingerprint:fingerprint,sha256,lastSeenShareVersion:2,lastSeenUpdatedAt:20,previous:{lastSeenShareVersion:2,lastSeenUpdatedAt:10,lastSeenFingerprint:'different'}}).code,'trainer-preferences/seen-conflict');});
test('grant and revoke deny self grants and cross-owner requests and remain preference-independent',()=>{const api=domain();assert.equal(api.approvedViewerGrant({...auth,ownerUid:'uid-a',viewerUid:'uid-a',action:'grant',targetDirectoryVerified:true}).code,'share-visibility/self-grant-denied');assert.equal(api.approvedViewerGrant({...auth,ownerUid:'uid-owner',viewerUid:'uid-b',action:'grant',targetDirectoryVerified:true}).code,'trusted-backend/grant-owner-denied');const grant=api.approvedViewerGrant({...auth,ownerUid:'uid-a',viewerUid:'uid-b',action:'grant',targetDirectoryVerified:true});assert.equal(grant.ok,true);assert.deepEqual(Array.from(grant.preferenceTargets),[]);assert.equal(api.approvedViewerGrant({...auth,ownerUid:'uid-a',viewerUid:'uid-b',action:'grant',targetDirectoryVerified:true,currentGrant:true}).status,'idempotent');});
test('legacy profile flags never grant admin authority',()=>{const value=domain().approvedViewerGrant({...auth,ownerUid:'uid-owner',viewerUid:'uid-b',action:'grant',targetDirectoryVerified:true,legacyIsAdmin:true,legacyIsOwner:true});assert.equal(value.code,'trusted-backend/grant-owner-denied');});
test('App Check and idempotency request IDs are mandatory in enforcement mode',()=>{const api=domain();assert.equal(api.reserveHandle({authUid:'uid-a',requestId:'x',requestedHandle:'Test'}).code,'trusted-backend/app-check-required');assert.equal(api.reserveHandle({authUid:'uid-a',appCheckValid:true,requestedHandle:'Test'}).code,'trusted-backend/request-id-invalid');assert.equal(api.reserveHandle({authUid:'uid-a',appCheckValid:false,appCheckRequired:false,requestId:'rollout',requestedHandle:'Test'}).ok,true);});
test('rename preserves UID ownership and returns a fixed atomic target allowlist',()=>{const value=domain().renameHandle({...auth,accountUid:'uid-a',currentClaimUid:'uid-a',currentHandle:'OldName',requestedHandle:'NewName'});assert.equal(value.ok,true);assert.equal(value.atomic,true);assert.equal(value.identityReassignment,false);assert.equal(value.allowedTargets.length,4);});
test('arbitrary path input is ignored in favor of fixed target allowlists',()=>{const value=domain().reserveHandle({...auth,requestedHandle:'TestUser',path:'admins/uid-a'});assert.deepEqual(Array.from(value.allowedTargets),['accounts/{authUid}','shareDirectory/{normalizedHandle}']);assert.doesNotMatch(JSON.stringify(value),/admins/);});
test('structured audit events retain codes and timing without identity or payload data',()=>{const value=domain().redactedAuditEvent({operation:'handle_reservation',status:'collision',code:'trusted-backend/handle-collision',durationMs:12.4,uid:'secret',payload:{trainerName:'secret'}});assert.deepEqual({...value},{schemaVersion:1,operation:'handle_reservation',status:'collision',errorCode:'trusted-backend/handle-collision',durationMs:12,identityRedacted:true,payloadRedacted:true});});
test('contracts expose no network Firebase or bulk API',()=>{const source=fs.readFileSync(path.join(root,'js/domain/trustedBackendContracts.js'),'utf8');assert.doesNotMatch(source,/fetch\s*\(|firebase-admin|https?:\/\/|set\s*\(|update\s*\(|remove\s*\(|bulk/i);});
