const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('fs');
const path=require('path');
const vm=require('vm');
const root=path.resolve(__dirname,'..');
function domain(){const context={window:{}};vm.createContext(context);for(const file of ['js/domain/trainerNames.js','js/domain/identityReconciliation.js'])vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),context);return context.window.PogoDomain.identityReconciliation;}
function base(name='Trainer',uid='uid-1'){
  return{loginDirectory:{[name]:{authReady:true}},users:{[name]:{authUid:uid}},authIndex:{[uid]:{username:name,lastSeen:1}},admins:{},authInput:{schemaVersion:1,identities:[{uid,disabled:false,emailVerified:false,providers:['password'],expectedSyntheticEmailMatches:true}]}};
}
function record(input,name='Trainer'){const result=domain().reconcileIdentitySources(input);assert.equal(result.ok,true);return result.value.records.find(item=>item.trainerName===name);}
test('positive corroboration from every required source is ready and never seed eligible',()=>{const item=record(base());assert.equal(item.classification,'ready_for_mapping');assert.equal(item.seedEligible,false);});
test('conflict-first precedence covers normalized duplicates and shared UID',()=>{const input=base('Trainer','uid-1');input.loginDirectory.trainer={authReady:true};input.users.trainer={authUid:'uid-1'};input.authIndex['uid-2']={username:'trainer'};const item=record(input,'Trainer');assert.equal(item.classification,'duplicate_or_conflicting');assert.ok(item.reasonCodes.includes('normalized_handle_collision'));assert.ok(item.reasonCodes.includes('uid_claimed_by_multiple_usernames'));});
test('multiple authIndex UIDs and duplicate Auth identities are explicit conflicts',()=>{const input=base();input.authIndex['uid-2']={username:'Trainer'};let item=record(input);assert.ok(item.reasonCodes.includes('username_has_multiple_auth_index_uids'));delete input.authIndex['uid-2'];input.authInput.identities.push({...input.authInput.identities[0]});item=record(input);assert.ok(item.reasonCodes.includes('duplicate_auth_identity_uid'));});
test('inconsistent bidirectional mappings precede missing and manual concerns',()=>{const input=base();input.authIndex['uid-1'].username='Other';input.loginDirectory.Trainer.authReady=false;const item=record(input);assert.equal(item.classification,'inconsistent_username_uid');assert.deepEqual([...item.reasonCodes],['uid_index_username_mismatch']);});
test('missing UID binding covers absent user UID and orphan index records',()=>{const input=base();delete input.users.Trainer.authUid;const item=record(input);assert.equal(item.classification,'missing_uid_binding');assert.ok(item.reasonCodes.includes('user_uid_missing'));input.authIndex.orphan={};const result=domain().reconcileIdentitySources(input);assert.equal(result.value.records.find(x=>x.internalKey==='authIndex:orphan').classification,'missing_uid_binding');});
test('records absent from loginDirectory are legacy or inactive',()=>{const input=base();delete input.loginDirectory.Trainer;assert.equal(record(input).classification,'legacy_or_inactive');});
test('absent and incomplete Auth inputs prevent readiness',()=>{const absent=base();delete absent.authInput;assert.deepEqual(Array.from(record(absent).reasonCodes),['auth_source_absent']);const incomplete=base();incomplete.authInput.identities=[];assert.deepEqual(Array.from(record(incomplete).reasonCodes),['auth_identity_missing']);});
test('protected admins and legacy privileged profiles require manual review',()=>{const input=base();input.admins['uid-1']=true;input.users.Trainer.isOwner=true;const item=record(input);assert.equal(item.classification,'manual_review');assert.ok(item.reasonCodes.includes('protected_admin'));assert.ok(item.reasonCodes.includes('legacy_privileged_profile_flag'));});
test('disabled, uncorroborated, not-ready and malformed Auth facts block readiness',()=>{for(const mutate of [i=>i.authInput.identities[0].disabled=true,i=>i.authInput.identities[0].expectedSyntheticEmailMatches=false,i=>i.loginDirectory.Trainer.authReady=false,i=>i.authInput.identities[0].providers=[]]){const input=base();mutate(input);assert.equal(record(input).classification,'manual_review');}});
test('normalization uncertainty and illegal Firebase keys block automatic readiness',()=>{const spaced=base(' Trainer ');assert.equal(record(spaced,' Trainer ').classification,'manual_review');const full=base('Ｔｒａｉｎｅｒ');assert.equal(record(full,'Ｔｒａｉｎｅｒ').classification,'manual_review');const illegal=base('Trainer.Name');assert.equal(record(illegal,'Trainer.Name').classification,'manual_review');});
test('duplicate Auth identity rows win over disabled and manual reasons',()=>{const input=base();input.authInput.identities.push({...input.authInput.identities[0],disabled:true});assert.equal(record(input).classification,'duplicate_or_conflicting');});
test('classification output is deterministic for identical snapshots',()=>{const first=domain().reconcileIdentitySources(base());const second=domain().reconcileIdentitySources(base());assert.equal(JSON.stringify(first),JSON.stringify(second));});
test('invalid sanitized Auth fields are rejected without accepting email or credentials',()=>{const input=base();input.authInput.identities[0].email='private@example.test';const result=domain().reconcileIdentitySources(input);assert.equal(result.ok,false);assert.equal(result.error.code,'forbidden_auth_input_field');});
