'use strict';

// This is an archive contract, not an application or Firebase schema.
// Only the small JSON Schema subset used below is interpreted by format.cjs.
const text=(maxLength=256)=>({type:'string',maxLength});
const id={type:'string',minLength:1,maxLength:700,pattern:'^[^\\u0000-\\u001f\\u007f]+$'};
const uid={type:'string',minLength:1,maxLength:128,pattern:'^[A-Za-z0-9_-]+$'};
const hash={type:'string',pattern:'^[a-f0-9]{64}$'};
const integer={type:'integer',minimum:0,maximum:Number.MAX_SAFE_INTEGER};
const bool={type:'boolean'};
const literal=value=>({const:value});
const enumeration=(...values)=>({enum:values});
const array=items=>({type:'array',items,maxItems:20000});
const nullable=schema=>({anyOf:[{type:'null'},schema]});
const object=(properties,optional=[])=>({type:'object',properties,required:Object.keys(properties).filter(key=>!optional.includes(key)),additionalProperties:false});
const dictionary=values=>({type:'object',additionalProperties:values,maxProperties:20000});
const timestamp={type:'string',pattern:'^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}Z$'};
const priority=enumeration('','H','M','L');
const category=enumeration('wishlist','dynamax','gmax','costumes');
const tradeValues=object({priority,variant:text(160),gender:enumeration('','m','f'),lucky:bool,xxl:bool,xxs:bool,shiny:bool,backgroundId:text(160),sortOrder:{...integer,maximum:100000},quantity:{...integer,minimum:1,maximum:999},note:text(160),mirror:bool});
const identity=object({surface:enumeration('my-list','special-board'),lane:enumeration('wishlist','dynamax','gmax','costumes','looking-for','for-trade'),catalogId:id});
const metadata=value=>dictionary({anyOf:[value,dictionary(value)]});
const wireBase={schemaVersion:literal(1),ownerUid:uid,entityType:enumeration('tradeEntry','favorite','tag'),entityId:id,identity:{anyOf:[identity,object({targetUid:uid}),object({tagId:id})]},generation:{...integer,minimum:1},revision:{...integer,minimum:1},deleted:bool,createdAt:integer,updatedAt:integer,values:{anyOf:[tradeValues,object({displayName:text(64),tagIds:dictionary(bool)},['tagIds']),object({label:text(40)})]},fieldRevisions:metadata({...integer,minimum:1}),fieldMutations:metadata(id),fieldMutationHashes:metadata(hash),lifecycleMutation:id,lifecycleMutationHash:hash,deletedAt:integer};
const wire=object(wireBase,['deletedAt']);
const patch=dictionary({anyOf:[text(160),bool,integer]});
const operation=object({schemaVersion:literal(1),operationId:id,ownerUid:uid,entityType:enumeration('tradeEntry','favorite','tag'),entityId:id,kind:enumeration('add','patch','delete'),baseGeneration:integer,generation:integer,baseFieldRevisions:dictionary(integer),patch,identity:nullable(wireBase.identity),clientAt:integer,inputHash:hash});
const queuedOperation=object({ownerUid:uid,operationId:id,status:enumeration('pending','sending','blocked','conflict','resolved','acknowledged'),attempts:integer,nextAttemptAt:integer,lastErrorCode:text(160),createdAt:integer,updatedAt:integer,operation,serverRevision:integer},['serverRevision']);
const conflict=object({conflictId:id,code:text(160),operationId:id,ownerUid:uid,entityType:wireBase.entityType,entityId:id,generation:integer,fields:array(id),currentRevision:integer,createdAt:integer,resolved:bool,resolvedAt:integer},['resolvedAt']);
const recovery=object({ownerUid:uid,candidateId:id,schemaVersion:literal(1),reason:text(160),entityType:wireBase.entityType,entityId:id,identity:{anyOf:[wireBase.identity,object({targetUid:literal('')}),object({surface:enumeration('my-list','special-board'),lane:identity.properties.lane,catalogIdUnresolved:literal(true)})]},values:wireBase.values,source:enumeration('legacy-local','legacy-remote','legacy-queue','legacy-local-board','legacy-remote-board','legacy-queue-board','legacy-history','legacy-favorite','legacy-tag','canonical'),createdAt:integer,resolved:bool,resolvedAt:integer},['resolvedAt']);
const profileValues=object({friendCode:text(32),bio:text(120),discord:text(40),avatarPokemon:text(120),wallpaper:text(80)});
const declaration=object({intent:enumeration('lf','ft'),category,name:text(200),p:priority,mod:text(160),gender:enumeration('','m','f'),backgroundId:text(160),note:text(160),lucky:bool,shiny:bool,xxl:bool,xxs:bool});
const publicValue=object({p:priority,mod:text(160),lucky:bool,shiny:bool,xxl:bool,xxs:bool,backgroundId:text(160)});
const listMap=dictionary({anyOf:[text(512),publicValue]});
const publicSnapshot=object({version:enumeration(1,2),username:id,profile:object({friendCode:text(32),bio:text(120),discord:text(40),avatarPokemon:text(120),lastUpdated:nullable(integer)}),lists:object({wishlist:listMap,dynamax:listMap,gmax:listMap,costumes:listMap}),publishedListTypes:array(category),updatedAt:integer,declarations:array(declaration),declarationCount:integer},['declarations','declarationCount']);
const favorite=object({key:id,displayName:text(64),targetUid:uid,tagIds:array(id),createdAt:integer,updatedAt:integer},['targetUid']);
const snapshot=object({seenAt:integer,targetUid:text(128),snapshot:{anyOf:[object({lists:object({wishlist:listMap,dynamax:listMap,gmax:listMap,costumes:listMap}),declarations:array(declaration),updatedAt:nullable(integer)},['declarations']),publicSnapshot]}});
const history=object({version:literal(3),schemaVersion:literal(3),migrationVersion:literal(3),owner:object({uid,username:id}),favorites:array(favorite),recent:array(object({key:id,displayName:text(64),openedAt:integer})),snapshots:dictionary(snapshot),tags:dictionary(object({id,label:text(40),normalizedLabel:text(40),createdAt:integer,updatedAt:integer})),syncState:literal('local-only'),migration:object({skippedFavorites:integer,skippedRecents:integer})});
const evidence=object({evidenceId:id,ownerUid:uid,kind:enumeration('canonical-meta','auth-index-pair','alias-proof','access-link','retired-uid-fence','migration-review'),observedAt:integer});
const provenance=object({accountId:uid,ownerUid:uid,currentHandle:id,authority:literal('accountSync-v1'),evidence:array(evidence),aliases:array(object({handle:id,ownerUid:uid,validFrom:integer,validUntil:nullable(integer),evidenceId:id})),accessMethods:array(object({kind:enumeration('legacy-pin','google'),ownerUid:uid,state:enumeration('linked','revoked'),providerSubjectKey:nullable(hash),credentialEpoch:integer,observedAt:integer,evidenceId:id})),retiredUids:array(object({uid,replacementUid:uid,retiredAt:integer,evidenceId:id}))});
const catalog=object({version:literal('synthetic-reviewed-v1'),entries:array(object({catalogId:id,speciesId:{...integer,minimum:1,maximum:1025},name:id,formId:text(160),costumeId:text(160),regionalForm:text(16),maxState:enumeration('','dynamax','gmax'),allowedGenders:array(enumeration('','m','f'))}))});
const meta=object({schemaVersion:literal(1),ownerUid:uid,featureVersion:literal(1),initialized:literal(true),initializedAt:integer,updatedAt:integer});
const migrationRecord=object({schemaVersion:literal(1),ownerUid:uid,deviceMigrationId:id,sourceFingerprint:hash,deviceInstallHash:hash,createdAt:integer,completedAt:integer,seedCount:integer,candidateCount:integer,verified:bool,legacyRetained:bool});
const recoveryReview=object({schemaVersion:literal(1),kind:literal('recovery-review-acceptance'),ownerUid:uid,trainerUsername:id,evidenceFingerprint:hash,candidateCount:{...integer,minimum:1},acceptedAt:integer});
const legacyBoardEntry=object({name:id,dn:text(256),no:nullable(integer),p:priority,priority,mod:text(160),variant:text(160),gender:enumeration('','m','f'),lucky:bool,xxl:bool,xxs:bool,shiny:bool,mirror:bool,backgroundId:text(160),note:text(160),qty:integer,quantity:integer,sortOrder:integer,catalogId:id},['dn','no','p','priority','mod','variant','gender','lucky','xxl','xxs','shiny','mirror','backgroundId','note','qty','quantity','sortOrder','catalogId']);
const legacyBoard=object({lf:array(legacyBoardEntry),ft:array(legacyBoardEntry)});
const ownedLists=object({wishlist:listMap,dynamax:listMap,gmax:listMap,costumes:listMap});
const localOrder=object({version:literal(1),owner:object({uid,username:id}),priorities:object({H:array(id),M:array(id),L:array(id),U:array(id)})});
const legacyQueueRecord=object({path:id,kind:enumeration('my-list-update','set'),data:{anyOf:[dictionary(nullable(text(512))),text(512),nullable(profileValues),legacyBoard]},ts:integer});
const legacySnapshot=object({capturedAt:integer,legacyRemoteLists:ownedLists,legacyLocalLists:ownedLists,legacyRemoteBoard:legacyBoard,legacyLocalBoard:legacyBoard,legacyQueue:dictionary(legacyQueueRecord),orders:dictionary(localOrder),favorites:array(favorite),tags:history.properties.tags});
const journalMeta=object({ownerUid:uid,name:{anyOf:[enumeration('provider-profile-pending-v1','provider-publication-pending-v1','migration-complete'),{type:'string',pattern:'^legacy-source:migration_[a-f0-9]{64}$'}]},value:{anyOf:[object({schemaVersion:literal(1),ownerUid:uid,values:object({friendCode:text(14),bio:text(120),discord:text(40),avatarPokemon:text(120)}),baseRevision:integer,queuedAt:integer}),object({schemaVersion:literal(1),ownerUid:uid,rows:array(object({entryId:id,...identity.properties,...tradeValues.properties},Object.keys(tradeValues.properties))),fingerprint:hash,queuedAt:integer}),migrationRecord,legacySnapshot]}});
const device=object({deviceId:id,ownerUid:uid,capturedAt:timestamp,sourceVersions:object({journal:literal(1),history:literal(3),sessionCache:literal(2),legacyQueue:literal(2),order:literal(1)}),history,journal:object({entities:array(wire),operations:array(queuedOperation),conflicts:array(conflict),recoveryCandidates:array(recovery),meta:array(journalMeta)}),legacyQueue:object({entries:array(legacyQueueRecord),quarantined:array(legacyQueueRecord)}),cachedOwnedLists:object({wishlist:listMap,dynamax:listMap,gmax:listMap,costumes:listMap}),orders:array(object({lane:category,version:literal(1),owner:object({uid,username:id}),priorities:object({H:array(id),M:array(id),L:array(id),U:array(id)})})),viewedSnapshots:array(object({lane:category,trainerName:id,keys:array(id),values:listMap,savedAt:integer})),preferences:object({language:enumeration('en','de','es','ja'),theme:enumeration('auto','dark','light'),searchLocale:enumeration('en','de','es','ja'),exportStyle:text(80),safeTransferDefault:bool})});
const historicalRecord=object({recordId:id,ownerUid:uid,kind:enumeration('retired-sync-entity','inventory','trade','background'),sourcePath:id,disposition:literal('inert-only'),value:{anyOf:[wire,object({name:id,gender:enumeration('','m','f'),qty:{...integer,maximum:999},mirrorOnly:bool,dontNeedBack:bool,giveaway:bool,note:text(160),backgroundId:text(160),shiny:bool,lucky:bool,xxl:bool,xxs:bool}),object({tradeId:id,partnerHandle:id,pokemonName:id,quantity:integer,status:enumeration('planned','completed','cancelled'),note:text(160),scheduledAt:integer}),object({name:id,backgroundId:id,note:text(160)})]}});
const disposition=object({path:id,action:enumeration('preserved','inert','excluded-secret','derived','non-restorable'),reason:text(512)});
const payload=object({format:literal('trade-app-user-archive'),archiveSchemaVersion:literal(1),capture:object({kind:literal('offline-synthetic'),capturedAt:timestamp,snapshotId:id}),source:object({runtimeRelease:literal('2026-09-07.100'),sourceCommit:{type:'string',pattern:'^[a-f0-9]{40}$'},adapterVersion:literal(1),accountSyncSchema:literal(1),trainerHistorySchema:literal(3)}),provenance,catalog,canonical:object({meta,entities:array(wire),recoveryEvidence:object({migrations:array(migrationRecord),candidates:array(recovery),reviewAcceptances:array(recoveryReview)}),profile:object({ownerUid:uid,authority:enumeration('legacy-profile','accountSync-profile'),revision:nullable(integer),values:profileValues,updatedAt:integer}),publicShare:object({ownerUid:uid,status:enumeration('published','not-published','revoked'),snapshot:nullable(publicSnapshot)})}),knownDevices:array(device),historical:object({records:array(historicalRecord)}),dispositions:array(disposition),coverage:object({server:literal('synthetic-snapshot'),capturedDevices:array(id),otherDevices:literal('unknown-not-captured'),volatileUnsavedEdits:literal('not-captured')}),compatibility:object({minimumReaderVersion:literal(1),target:literal('isolated-filesystem-v1'),authentication:literal('reverify-never-recreate'),pendingWork:literal('quarantine-never-replay'),historical:literal('inert-only')})});
const archive=object({...payload.properties,integrity:object({algorithm:literal('sha256'),canonicalization:literal('trade-archive-json-v1'),sections:dictionary(hash),payloadHash:hash})});
const schema={$schema:'https://json-schema.org/draft/2020-12/schema',$id:'urn:trade-app:offline-synthetic-archive:v1',title:'Trade App offline synthetic archive v1',...archive};
// The reader uses the expanded, closed shape above. Emit equivalent standard
// JSON Schema with named definitions so humans do not have to read repeated wire
// record definitions. Semantic ownership/catalog/hash checks remain mandatory.
const definitions={uid,id,hash,timestamp,tradeValues,tradeIdentity:identity,accountSyncEntityV1:wire,accountSyncOperationV1:operation,queuedOperation,conflict,recoveryCandidate:recovery,profileValues,publicDeclaration:declaration,publicSnapshot,history,provenance,catalog,migrationRecord,recoveryReview,legacyBoard,ownedLists,localOrder,legacyQueueRecord,legacySnapshot,journalMeta,device,historicalRecord,disposition};
const names=new Map(Object.entries(definitions).map(([name,value])=>[value,name]));
function compact(value,defining=false){
  if(Array.isArray(value))return value.map(item=>compact(item));
  if(!value||typeof value!=='object')return value;
  if(!defining&&names.has(value))return{$ref:`#/$defs/${names.get(value)}`};
  return Object.fromEntries(Object.entries(value).map(([key,item])=>[key,compact(item)]));
}
const schemaDocument={...compact(schema),$defs:Object.fromEntries(Object.entries(definitions).map(([name,value])=>[name,compact(value,true)]))};
module.exports={schema,schemaDocument,payloadSchema:payload,wireSchema:wire,operationSchema:operation};
