(function(global){
  const root=global.PogoLocales=global.PogoLocales||{};
  root.ja=Object.freeze({...root.en,
    'data.loading':'{resource}を読み込んでいます…','data.empty':'{resource}はありません。','data.readError':'{resource}を読み込めませんでした。もう一度お試しください。','data.offline':'オフラインです。端末に保存されたデータは引き続き利用できます。','data.retrying':'再試行しています…','data.permissionDenied':'このコンテンツを表示する権限がありません。','data.signedOut':'セッションが終了しました。もう一度ログインしてください。','data.stale':'最新データを取得できないため、保存済みデータを表示しています。',
    'app.updateRequired':'新しいバージョンがあります。更新して続行してください。','app.reloadAction':'アプリを更新','app.mainSections':'メインセクション','app.install':'インストール','app.installLabel':'アプリをインストール','app.whatsNew':'新着情報','app.theme':'テーマを切り替え','app.openProfile':'プロフィールを開く','app.dismiss':'このセッションでは閉じる',
    'account.title':'アカウント','account.openMenu':'アカウントメニューを開く','account.closeMenu':'アカウントメニューを閉じる','account.signedInAs':'ログイン中','account.settings':'設定','account.signOut':'ログアウト','account.language':'言語','account.languageSettings':'言語設定','account.closeSettings':'設定を閉じる','settings.publicDescription':'この端末に保存する表示言語を選択します。',
    'login.subtitle':'NYC コミュニティ交換リスト','login.disclaimer':'非公式のコミュニティツールです。Niantic、Nintendo、株式会社ポケモンとは関係ありません。','login.username':'トレーナー名','login.usernamePlaceholder':'トレーナー名を入力または選択…','login.usernameSuggestions':'トレーナー名の候補','login.pin':'PIN','login.pinPlaceholder':'6桁のPIN','login.signIn':'ログイン','login.newUserHelp':'初めての方は、まず参加申請をしてください。承認後、管理者から初回用の6桁PINが届きます。','login.existingUserHelp':'承認済みでPINが必要な場合は、管理者に本人確認を保持したPIN再設定を依頼してください。','login.trouble':'ログインでお困りですか？','login.requestAccess':'参加を申請','login.directoryLoading':'承認済みトレーナー名を読み込んでいます…','login.directoryError':'承認済みトレーナー名を読み込めませんでした。','login.directoryRetry':'再試行','login.directoryNoMatch':'一致する承認済みトレーナー名がありません。正確な名前を入力することもできます。','login.directoryUnknown':'このトレーナー名は承認済みログイン一覧にありません。','login.directoryReady':'利用可能','login.directoryPending':'設定中',
    'nav.myList':'マイリスト','nav.findTrainer':'トレーナー検索','nav.events':'イベント','nav.legacyInventory':'旧インベントリ','nav.settings':'設定','nav.admin':'管理','nav.myListShort':'リスト','nav.findTrainerShort':'検索','nav.eventsShort':'イベント','nav.legacyInventoryShort':'持ち物','nav.settingsShort':'設定','nav.adminShort':'管理',
    'trainer.findTitle':'トレーナー検索','trainer.findDescription':'トレーナー名を検索し、公開リストの閲覧や自分のリストとの比較ができます。','trainer.findPlaceholder':'トレーナー名を検索','trainer.findAction':'検索','trainer.searchStart':'トレーナー名を入力してください。','trainer.searching':'検索しています…','trainer.noMatch':'一致するトレーナーが見つかりません。','trainer.notPublished':'このトレーナーはまだリストを公開していません。','trainer.sharedUnavailable':'このトレーナーの共有リストは利用できません。','trainer.shareNeedsRepublishing':'この共有リストはトレーナーによる再公開が必要です。','trainer.sharedMalformed':'この共有リストは未対応の形式です。再公開が必要です。','trainer.sharedReadFailed':'共有リストを読み込めませんでした。もう一度お試しください。','trainer.compareAction':'マイリストと比較','trainer.favoriteAdd':'お気に入りに追加','trainer.favoriteRemove':'お気に入りから削除','trainer.favoritesTitle':'お気に入りのトレーナー','trainer.recentTitle':'最近見たトレーナー','trainer.deviceLocalHelp':'お気に入り、履歴、変更履歴はこの端末にのみ保存されます。','trainer.deviceLocalTitle':'非公開のトレーナーツール','trainer.syncComingLater':'端末間同期 — 今後対応予定','trainer.initialHint':'公開トレーナー一覧を検索するか、最近見たトレーナーやお気に入りを開いてください。','trainer.favoriteAdded':'この端末のお気に入りに追加しました。','trainer.favoriteRemoved':'この端末のお気に入りから削除しました。','trainer.listUnavailable':'リストを利用できません','trainer.openAction':'トレーナーを開く','trainer.suggestionsLabel':'トレーナー候補','trainer.unreadChanges':'共有リストに未読の変更があります。',
    'strings.ownDescription':'Pokémon GO の検索文字列はマイリストから自動更新されます。','strings.myListHelp':'優先度別の文字列をコピーするか、「まとめて表示」でリスト全体を確認できます。','strings.title':'検索文字列','strings.emptyTitle':'検索文字列はまだありません','strings.emptyHelp':'リストに項目を追加すると、優先度別とキラ図鑑用の文字列が作成されます。','strings.copied':'コピーしました','strings.copySuccess':'検索文字列をコピーしました。','strings.copyFailed':'コピーできませんでした。テキストを手動で選択してください。',
    'share.ownerTitle':'共有リストの更新が必要です','share.ownerPrivateSafe':'非公開リストはそのままです。所有リストの読み込み完了後にのみ再公開してください。','share.ownerRepublishAction':'共有リストを再公開','share.ownerRepublishing':'再公開しています…','share.ownerRepublishSuccess':'共有リストを再公開して確認しました。','share.ownerRepublishFailed':'完全なデータを確認できなかったため、共有リストは変更されませんでした。',
    'inventory.legacyTitle':'旧インベントリ','inventory.legacyDescription':'保存済みインベントリは読み取り専用で保持されています。必要なときに書き出せます。','inventory.legacyEmpty':'このアカウントには旧インベントリがありません。','inventory.legacyReadOnly':'旧インベントリは読み取り専用です。変更は保存されませんでした。','inventory.exportAction':'CSVを書き出す','inventory.filterPlaceholder':'インベントリを絞り込む…','inventory.sectionTitle':'保存済みインベントリ',
    'events.title':'イベント','events.description':'開催中および今後のPokémon GOイベント。','events.loading':'今後のイベントを読み込んでいます…','events.empty':'現在、今後のイベントはありません。','events.error':'イベントを読み込めませんでした。後でもう一度お試しください。','events.groupNow':'開催中','events.groupSoon':'まもなく開始','events.groupLater':'今後','events.filterAll':'すべて','events.filterRaids':'レイド','events.filterMax':'マックスバトル','events.filterGbl':'GOバトルリーグ','events.filterResearch':'リサーチ','events.filterGeneral':'一般','events.details':'詳細','events.filtersLabel':'イベントの種類','events.filteredEmpty':'このフィルターに一致するイベントはありません。','events.offline':'オフライン中はイベントを利用できません。接続後に再試行してください。',
    'settings.title':'設定','settings.description':'プロフィール、アプリの状態、表示、セッションを管理します。','settings.profileAction':'プロフィールを編集','settings.healthAction':'アプリの状態','settings.shortcutsAction':'キーボードショートカット','settings.logoutAction':'ログアウト','settings.languageTitle':'言語','settings.languageDescription':'表示言語はこの端末にのみ保存されます。','settings.languageLabel':'表示言語','settings.languageSaved':'言語設定をこの端末に保存しました。','settings.localToolsTitle':'トレーナー設定','settings.localToolsDescription':'お気に入りと履歴はこの端末内だけに保存されます。非公開タグと端末間同期はまだ有効ではありません。','settings.syncComingLater':'端末間同期 — 今後対応予定',
    'myList.listTitle':'マイリスト','myList.filterPlaceholder':'マイリストを絞り込む…','myList.addTitle':'ポケモンを追加','myList.addHelp':'多く追加するときは、優先度とフラグを保持する連続追加を利用できます。','myList.searchPlaceholder':'ポケモンを検索…','myList.priority':'優先度','myList.flags':'フラグ','myList.advanced':'詳細','myList.notesPlaceholder':'メモ：メス、オス、シャドウ…','myList.addAction':'追加','myList.importAction':'文字列を読み込む','myList.speedAdd':'連続追加','myList.exportAction':'書き出す','myList.bulkEdit':'一括編集','myList.noMatches':'一致する項目がありません','myList.clearFilter':'すべて表示するには絞り込みを解除してください。','myList.emptyTitle':'まだ何もありません','myList.emptyHelp':'ポケモンを検索し、優先度を選んでこのリストに追加してください。','myList.count':'（{count}件）','myList.filteredCount':'（{total}件中{visible}件）',
    'list.wishlist':'交換','list.dynamax':'ダイマックス','list.gigantamax':'キョダイマックス','list.others':'その他','priority.high':'高','priority.medium':'中','priority.low':'低',
    'status.localOnlyTitle':'端末内モード','status.localOnlyBody':'編集内容はこの端末に安全に保存されています。再ログインすると保留中の変更（{count}件）を同期できます。','status.signBackIn':'再ログイン',
    'trainer.syncTitle':'保存したトレーナーの同期','trainer.syncPreview':'同期する前に、この端末とクラウドに保存されている内容を確認します。','trainer.syncDeviceCount':'この端末','trainer.syncCloudCount':'クラウド','trainer.syncPending':'同期を待っている変更があります。','trainer.syncSuccess':'保存したトレーナーは最新です。','trainer.syncError':'同期を完了できませんでした。端末のコピーは変更されていません。','trainer.syncConflict':'確認が必要な変更があります。','trainer.syncLastSuccess':'前回の同期: {time}','trainer.syncLastSuccessNever':'まだ同期されていません','trainer.syncRemoveCloudKeepLocal':'クラウドのコピーを削除し、この端末には残す','trainer.syncRemoveCloudAndLocal':'クラウドと端末のコピーを削除','trainer.syncState.local-only':'この端末に保存','trainer.syncState.pending-sync':'同期中…','trainer.syncState.synced':'同期済み','trainer.syncState.conflict':'確認が必要','trainer.syncState.sync-error':'同期できませんでした',
    'trainer.syncStatus.localOnlyDetail':'端末間同期はまだ有効ではありません。保存したトレーナーはこの端末に残ります。','trainer.syncStatus.pendingDetail':'この端末の変更を非公開のクラウドコピーに保存しています。','trainer.syncStatus.syncedDetail':'非公開の保存済みトレーナーデータは最新のクラウドコピーと一致しています。','trainer.syncStatus.conflictDetail':'この端末と別の端末で行われた変更の残し方を選びます。','trainer.syncStatus.errorDetail':'端末のコピーは安全です。準備ができたら詳細から再試行できます。',
    'trainer.syncConflict.unavailable':'同期の詳細は利用できません。','trainer.syncConflict.note.title':'2つの非公開メモを確認してください','trainer.syncConflict.note.local':'この端末で非公開メモが変更されました。','trainer.syncConflict.note.remote':'別の端末で非公開メモが変更されました。','trainer.syncConflict.note.preserve':'両方を残すと、どちらかを置き換える前に確認できます。','trainer.syncConflict.note.discard':'一方を選ぶと、確認後にもう一方のメモは破棄されます。','trainer.syncConflict.tagRename.title':'2つのタグ名を確認してください','trainer.syncConflict.tagRename.local':'この端末で非公開タグ名が変更されました。','trainer.syncConflict.tagRename.remote':'別の端末で同じ非公開タグに別の名前が付けられました。','trainer.syncConflict.tagRename.preserve':'一方を別の非公開タグとして残し、両方の名前を保持できます。','trainer.syncConflict.tagRename.discard':'一方を選ぶと、確認後にもう一方の名前は破棄されます。','trainer.syncConflict.favorite.title':'このお気に入りは別の端末で変更されました','trainer.syncConflict.favorite.local':'この端末がお気に入りを変更しようとしました。','trainer.syncConflict.favorite.remote':'先にクラウドの最新コピーが変更されました。','trainer.syncConflict.favorite.preserve':'最新のコピーを残し、必要なら端末の変更をもう一度試します。','trainer.syncConflict.favorite.discard':'最新のコピーを残すと、古い端末の変更は適用されません。','trainer.syncConflict.offline.title':'オフライン編集と新しい変更が競合しています','trainer.syncConflict.offline.local':'この端末はオフライン中に変更しました。','trainer.syncConflict.offline.remote':'別の端末がより新しい変更を保存しました。','trainer.syncConflict.offline.preserve':'両方を残し、どちらかを置き換える前に比較できます。','trainer.syncConflict.offline.discard':'一方を選ぶと、確認後にもう一方は破棄されます。','trainer.syncConflict.version.title':'続ける前にアプリを更新してください','trainer.syncConflict.version.local':'このアプリでは最新の保存形式を安全に読み込めません。','trainer.syncConflict.version.remote':'クラウドコピーは新しいアプリで保存されました。','trainer.syncConflict.version.preserve':'更新しても両方のコピーは変更されません。','trainer.syncConflict.version.discard':'更新によってデータは破棄されません。',
    'trainer.syncChoice.keep-both':'両方のコピーを残す','trainer.syncChoice.use-device':'この端末のコピーを使う','trainer.syncChoice.use-cloud':'クラウドのコピーを使う','trainer.syncChoice.keep-current':'最新のコピーを残す','trainer.syncChoice.try-again':'端末の変更を再試行','trainer.syncChoice.refresh':'アプリを更新',
    'trainer.syncMigration.title':'この端末に保存したトレーナーを確認','trainer.syncMigration.reviewDevice':'この端末に保存された非公開トレーナーデータを確認します。','trainer.syncMigration.deviceCounts':'この端末のお気に入り、タグ、メモ、最近見たトレーナー、履歴の件数を確認します。','trainer.syncMigration.cloudCounts':'提供されたクラウドの件数を確認します。','trainer.syncMigration.summary':'自動で統合できる内容と確認が必要な内容を確認します。','trainer.syncMigration.nothingDeleted':'初回同期ではこの端末から何も削除されません。','trainer.syncMigration.confirmTitle':'プレビュー完了後にのみ確認してください。','trainer.syncMigration.unavailable':'初回同期はまだ利用できません。','trainer.syncCount.favorites':'お気に入り','trainer.syncCount.tags':'タグ','trainer.syncCount.notes':'非公開メモ','trainer.syncCount.recents':'最近見たトレーナー','trainer.syncCount.history':'履歴',
    'trainer.syncDelete.title':'削除する内容を選択','trainer.syncDelete.cloud-only.title':'クラウドコピーのみ削除','trainer.syncDelete.cloud-only.consequence':'非公開のクラウドコピーを削除し、この端末のコピーは残します。','trainer.syncDelete.cloud-and-device.title':'クラウドと端末のコピーを削除','trainer.syncDelete.cloud-and-device.consequence':'別の確認後に両方のコピーを削除します。','trainer.syncDelete.device-only.title':'この端末だけに残す','trainer.syncDelete.device-only.consequence':'クラウド同期を停止し、この端末のコピーを非公開で残します。','trainer.syncDelete.unavailable':'クラウド削除はまだ利用できません。',
    'common.cancel':'キャンセル','common.save':'保存','organizer.title':'トレーナーを整理','organizer.localOnly':'お気に入り、タグ、メモは現在この端末に保存されています。','organizer.close':'整理画面を閉じる','organizer.favoriteTrainer':'お気に入りのトレーナー','organizer.tags':'タグ','organizer.tagsHelp':'このトレーナーに付ける非公開タグを選べます。','organizer.privateNote':'非公開メモ','organizer.noteHelp':'このメモは端末内だけに保存され、共有リストやエクスポートには含まれません。','organizer.notePlaceholder':'非公開メモを追加…','organizer.noteLimit':'最大240文字','organizer.manageTags':'タグを管理','organizer.manageTagsHelp':'タグ名は非公開で、トレーナーデータを変更しません。','organizer.addTagPlaceholder':'新しいタグ','organizer.addTag':'タグを追加','organizer.organize':'お気に入りを整理','organizer.searchFavorites':'お気に入りのトレーナーまたはタグを検索','organizer.clearFilters':'フィルターを解除','organizer.filterTags':'選択したすべてのタグでお気に入りを絞り込む','organizer.noFavorites':'お気に入りのトレーナーはまだいません。','organizer.noMatches':'条件に一致するお気に入りはありません。','organizer.noTags':'非公開タグはまだありません。','organizer.savedLocal':'この端末に保存しました。','organizer.discardChanges':'保存していない変更を破棄しますか？','organizer.tagCreated':'非公開タグを作成しました。','organizer.tagRenamed':'非公開タグ名を変更しました。','organizer.tagDeleted':'非公開タグを削除しました。','organizer.deleteConfirm':'非公開タグ「{tag}」をすべてのお気に入りから削除しますか？','organizer.tagName':'タグ名: {tag}','organizer.renameTagNamed':'タグ「{tag}」の名前を変更','organizer.deleteTagNamed':'タグ「{tag}」を削除','organizer.tag-empty':'タグ名を入力してください。','organizer.tag-too-long':'タグ名は40文字以内にしてください。','organizer.tag-limit':'この端末のタグ上限24件に達しました。','organizer.tag-duplicate':'同じ名前のタグがすでにあります。','organizer.tag-missing':'そのタグは利用できません。','organizer.favorite-missing':'そのお気に入りは利用できません。','organizer.note-too-long':'非公開メモは240文字以内にしてください。','organizer.saveFailed':'端末内の変更を保存できませんでした。','settings.localToolsDescription':'お気に入り、最近見たトレーナー、非公開タグ、メモはこの端末にのみ保存されます。端末間同期はまだ有効ではありません。'
  });
})(window);
